[package]
name = "postbag"
version = "1.0.0-pre8"
authors = [
    "Sebastian Urban <surban@surban.net>",
    "James Munns <james@onevariable.com>",
]
edition = "2024"
readme = "README.md"
repository = "https://github.com/remoc-rs/postbag"
description = "💼 Postbag is a high-performance serde codec for Rust that provides efficient data encoding with configurable levels of forward and backward compatibility."
license = "Apache-2.0"
rust-version = "1.95"
categories = ["encoding"]
keywords = ["serde"]

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
base64 = "0.23"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(postbag_fast_compile)'] }
